### ISSUE TITLE
Connecting to GameJolt

### ISSUE THREAD

**Issue by SamtheGameDev23** [murikistudio/game-jolt-api#3] opened 2023-10-23 06:18 UTC
I've been trying ways to connect and it keeps giving me:

`E 0:00:29:0860   MainMenu2.gd:15 @ _on_gamejolt_login_button_pressed(): Signal 'time_completed' is already connected to given callable 'Node2D(MainMenu2.gd)::_on_GameJolt_time_completed' in that object.`

How do I fix it?

**Comment by joelgomes1994** [comment] 2023-10-23 18:39
Hello, @SamtheGameDev23 ! You should only connect signals once. Try to connect the `GameJolt.time_completed` signal at the script startup (inside `_ready`), then call `GameJolt.time()` to call the API endpoint, and finally get the result at the first argument on `_on_GameJolt_time_completed`.

```gdscript
# Connect the signal to the function
func _ready():
    GameJolt.time_completed.connect(_on_GameJolt_time_completed)


# Trigger API endpoint on button press
func _on_gamejolt_login_button_pressed():
    GameJolt.time()


# Receive the API response on the function parameter
func _on_GameJolt_time_completed(response: Dictionary):
    prints(response)
    # Do something with the response value...
```

There's also examples on the [documentation](https://github.com/murikistudio/game-jolt-api#handling-request-responses) using both `connect` and `await` formats.

_(I'll close the issue as it is not a bug report of feature request, but you can still reply here)._

**Closed as completed** 2023-10-23 18:43 UTC
Labels: question
